// ============================================================
// lang.js — Bilingual System (Part 12 - 添加转生翻译)
// ============================================================

const LANG = {
  zh: {
    // ---------- UI 核心 ----------
    rank: "军衔",
    stars: "战星",
    exp: "经验",
    gold: "金币",
    cp: "战斗力",
    kill: "击杀",
    boss: "敌军指挥官",
    autoFight: "战场",
    offlineEarning: "离线收益",
    doubleReward: "双倍领取",
    promotion: "晋升试炼",
    trialPass: "✅ 试炼通过！晋升成功！",
    trialFail: "❌ 试炼失败！继续战斗！",
    normalTrial: "标准试炼 50%",
    premiumTrial: "军费晋升 70%",
    watchAd: "观看广告 100%",
    starsFull: "★★★★★ 战星已满，准备晋升！",
    save: "存档",
    load: "读档",
    claim: "领取",
    confirm: "确认",
    cancel: "取消",

    // ---------- 晋升 ----------
    promoteNormal: "标准试炼",
    promoteGold: "军费晋升",
    promoteAd: "推荐信",
    promoteNormalDesc: "消耗经验，成功率50%",
    promoteGoldDesc: "消耗金币，成功率70%",
    promoteAdDesc: "观看广告，100%成功",
    failPenalty: "失败扣除50%经验",
    goldLost: "金币不退",
    guaranteed: "必定成功",

    // ---------- 故事 ----------
    storyTitle: "⭐ 战地日志",
    storySkip: "跳过",
    storyContinue: "继续 ▶",

    // ---------- 建筑 ----------
    building: "基地设施",
    goldMine: "金矿",
    ironMine: "铁矿",
    riceFarm: "稻田",
    barracks: "兵营",
    hospital: "战地医院",
    buildingMaxLevel: "已达当前军衔最大等级",
    notEnoughGold: "金币不足",
    buildingUpgraded: "设施升级成功！",
    buildingProduction: "基地产出",

    // ---------- 士兵 ----------
    soldier: "士兵",
    soldiers: "兵力",
    train: "训练",
    trainSoldier: "训练士兵",
    treat: "救治",
    treatWounded: "救治伤兵",
    wounded: "伤兵",
    totalSoldiers: "总兵力",
    soldierMax: "最大兵力",
    ricePerSecond: "稻米消耗/秒",
    trainCost: "训练消耗",
    healCost: "救治消耗",
    noWounded: "无伤兵",
    maxSoldiersReached: "已达最大兵力上限",
    notEnoughRice: "稻米不足",
    soldierTrained: "士兵训练完成！",
    soldierTrainedAd: "士兵训练完成！(广告加速)",
    soldierHealed: "伤兵救治完成！",
    soldierHealedAd: "伤兵救治完成！(广告加速)",
    soldierDied: "一名士兵在战斗中阵亡",

    // ---------- 舰队 ----------
    fleet: "舰队",
    fleetUpgrade: "升级战舰",
    fleetLocked: "未解锁",
    fleetLevel: "等级",
    fleetCp: "舰队火力",
    fleetMaxLevel: "已达最大等级",
    notEnoughIron: "铁矿不足",
    fleetUpgraded: "战舰升级成功！",
    fleetUpgradedAd: "战舰升级成功！(广告加速)",

    // ---------- 科技 ----------
    tech: "科技树",
    techPoint: "科技点",
    techUpgrade: "研究科技",
    techLocked: "未解锁",
    techMaxLevel: "已达最大等级",
    techEffectCp: "+战斗力",
    techEffectIncome: "+收入",
    techEffectArmor: "-士兵死亡率",
    techEffectRadar: "-Boss间隔",
    techEffectAI: "+战斗效率",
    techEffectBoss: "+Boss伤害",
    techEffectAll: "+全部收益",
    techUpgraded: "科技研究成功！",
    techUpgradedAd: "科技研究成功！(广告加速)",
    techPointGain: "获得科技点",
    notEnoughTechPoint: "科技点不足",

    // ---------- 装备 ----------
    equipment: "军备",
    equipUpgrade: "升级军备",
    equipLocked: "未解锁",
    equipMaxLevel: "已达最大等级",
    equipCp: "+战斗力",
    equipArmor: "-死亡率",
    equipIncome: "+收入",
    equipBoss: "+Boss伤害",
    equipEfficiency: "+战斗效率",
    equipAll: "+全属性",
    equipUpgraded: "军备升级成功！",
    equipUpgradedAd: "军备升级成功！(广告加速)",

    // ---------- 每日任务 ----------
    dailyQuest: "每日任务",
    dailyQuests: "每日任务",
    dailyReset: "每日重置",
    dailyProgress: "进度",
    dailyClaim: "领取奖励",
    dailyCompleted: "已完成",
    dailyIncomplete: "未完成",
    dailyReward: "奖励",
    dailyDone: "✅ 已完成",
    dailyClaimed: "已领取",

    // ---------- 签到 ----------
    loginCheckIn: "每日签到",
    loginDay: "签到第 {day} 天",
    loginStreak: "连续签到 {streak} 天",
    loginClaim: "签到领取",
    loginReward: "签到奖励",
    loginSpecial: "🎉 超级奖励！",
    loginAllClaimed: "🎉 已完成所有签到！",
    loginStreakBroken: "⚠️ 签到中断，已重置",
    loginAlreadyClaimed: "📅 今日已签到",

    // ---------- 成就 ----------
    achievement: "功勋",
    achievements: "功勋墙",
    achievementUnlocked: "🎖️ 功勋解锁！",
    achievementLocked: "未解锁",
    achievementProgress: "进度",
    achievementReward: "奖励",

    // ---------- 事件 ----------
    event: "战场事件",
    eventTitle: "⚡ 战场事件",
    eventClaim: "领取战利品",
    eventDismiss: "忽略",
    eventAdBonus: "📺 广告奖励 ×2",
    eventNoAd: "广告加载失败，已普通领取",
    eventBuff: "🔁 双倍收益增益",

// ===== 电影化事件翻译 - 中文 =====
// 🟢 好事件
evt_spy_intel: "🕵️ 暗影突击行动",
evt_spy_intel_desc: "代号：暗影。一名潜伏多年的间谍成功窃取了敌军的核心作战计划！",
evt_gold_mine: "⛏️ 黄金狂潮",
evt_gold_mine_desc: "勘探队在废弃矿区发现了储量惊人的黄金矿脉！",
evt_united_nations: "🌍 人道干预",
evt_united_nations_desc: "联合国派遣了一支人道主义救援舰队抵达前线。",
evt_scientist_joins: "👨‍🔬 天才降临",
evt_scientist_joins_desc: "诺贝尔奖得主艾琳·克劳斯博士决定加入你的研究团队！",
evt_morale_boost: "🎖️ 兄弟连",
evt_morale_boost_desc: "士兵们在一次联合行动后结下了深厚的情谊，士气空前高涨。",
evt_weapon_test: "🔫 泰坦计划",
evt_weapon_test_desc: "秘密武器项目'泰坦'测试取得圆满成功！",
evt_supply_drop: "📦 补给任务",
evt_supply_drop_desc: "代号'铁砧'的补给无人机成功穿越敌方防空网。",
evt_scout_returns: "🔭 深入敌后",
evt_scout_returns_desc: "侦察小队在敌后深处潜伏72小时后成功返回，带回关键情报。",
evt_enemy_armory: "💣 军火库突袭",
evt_enemy_armory_desc: "突击队成功渗透并引爆了敌军的战略军火库！",
evt_reinforcements: "🚁 骑兵到来",
evt_reinforcements_desc: "第7空中骑兵团抵达战场！风笛手吹响了集结号！",
evt_treasure_map: "🗺️ 失落的宝藏",
evt_treasure_map_desc: "士兵在一座废弃哨站中发现了一张标注着'黄金城'的古老地图。",
evt_training_camp: "🏋️ 新兵训练营",
evt_training_camp_desc: "新兵们在魔鬼教官的训练下完成了'地狱周'！",
evt_trading_post: "🏪 边境集市",
evt_trading_post_desc: "边境集市的商人带来了稀缺物资。",
evt_diplomatic_mission: "🤝 和平谈判",
evt_diplomatic_mission_desc: "外交使团成功与敌对势力达成临时和平协议。",
evt_engineering_breakthrough: "⚙️ 突破",
evt_engineering_breakthrough_desc: "工程团队在推进系统上取得了革命性突破！",
evt_medical_supplies: "💊 野战医院",
evt_medical_supplies_desc: "M*A*S*H野战医院运抵，医疗物资充足！",
evt_strategic_position: "🏔️ 高地",
evt_strategic_position_desc: "部队成功夺取了'君临山'这一战略要地！",
evt_war_hero: "🎖️ 荣誉勋章",
evt_war_hero_desc: "下士约翰·米勒因英勇作战被授予荣誉勋章！",
evt_crops_harvest: "🌾 丰收之月",
evt_crops_harvest_desc: "稻田迎来历史性大丰收，粮仓堆满！",
evt_iron_vein: "⛏️ 铁矿脉",
evt_iron_vein_desc: "在南部山脉发现了纯度极高的铁矿脉！",

// 🟡 普通事件
evt_civilian_plea: "👥 战争难民",
evt_civilian_plea_desc: "一群战争难民聚集在基地门口，请求庇护和食物。",
evt_merchant_visit: "🧳 黑市商人",
evt_merchant_visit_desc: "一名自称'狐狸'的黑市商人带来了'特别'的货物。",
evt_abandoned_base: "🏚️ 废墟哨站",
evt_abandoned_base_desc: "侦察兵发现了一座废弃的军事哨站，里面似乎还有可用物资。",
evt_recruit_volunteers: "🪖 志愿者",
evt_recruit_volunteers_desc: "战争的号角吹响，志愿者纷纷涌向征兵处。",
evt_pmc_contract: "📋 雇佣兵合同",
evt_pmc_contract_desc: "一家PMC公司提供了高额雇佣合同，任务：摧毁敌方雷达站。",
evt_refugee_camp: "⛺ 难民营",
evt_refugee_camp_desc: "在边境线上，一个难民营正在收容战争中的流离失所者。",
evt_lost_convoy: "🚚 遗弃的车队",
evt_lost_convoy_desc: "在沙漠中发现了一支被遗弃的补给车队，似乎遭遇了袭击。",
evt_deserters: "🏃 逃兵",
evt_deserters_desc: "三名逃兵在深夜投靠了你的部队，带来了敌军的情报。",
evt_radio_transmission: "📻 幽灵信号",
evt_radio_transmission_desc: "通讯站截获了一段加密的无线电信号，来源不明。",
evt_field_hospital: "🏥 战地医院",
evt_field_hospital_desc: "战地医院的医生们正在争分夺秒地抢救伤员。",
evt_old_soldier: "🧓 老兵",
evt_old_soldier_desc: "一名参加过三次战争的老兵前来报到，带来了丰富的战斗经验。",
evt_storm_warning: "🌩️ 风暴前夕",
evt_storm_warning_desc: "气象站报告：一场超强风暴正在逼近，请做好防护准备。",
evt_friendly_fire: "🔥 误击事件",
evt_friendly_fire_desc: "夜间巡逻中，哨兵误将友军当作敌军开火，造成了伤亡。",
evt_black_market: "🏴 黑市交易",
evt_black_market_desc: "在黑市上，有人愿意用铁和稻米交换金币。",
evt_supply_shortage: "📉 补给危机",
evt_supply_shortage_desc: "补给线被切断，前线物资告急！",
evt_secret_tunnel: "🚇 秘密隧道",
evt_secret_tunnel_desc: "一名工兵发现了一条通往敌军指挥部的废弃隧道！",
evt_ceasefire: "🕊️ 停火协议",
evt_ceasefire_desc: "双方在红十字会的调解下达成了为期72小时的临时停火。",
evt_ancient_ruins: "🏛️ 失落的文明",
evt_ancient_ruins_desc: "发现了一座属于失落文明的巨大遗迹，里面似乎有惊人的秘密。",
evt_diplomatic_incident: "📜 外交事件",
evt_diplomatic_incident_desc: "一名外交官在处理事务时造成了严重的外交风波。",
evt_wildlife_attack: "🐺 野兽袭击",
evt_wildlife_attack_desc: "基地外围遭到一群饥渴的沙狼袭击！",
evt_desert_storm: "🌪️ 沙漠风暴",
evt_desert_storm_desc: "一场巨大的沙漠风暴正在摧毁沿途的一切！",

// 🔴 坏事件
evt_enemy_air_raid: "✈️ 黑色星期二",
evt_enemy_air_raid_desc: "敌军发动了代号'黑色星期二'的大规模空袭！",
evt_convoy_ambushed: "💥 死亡公路",
evt_convoy_ambushed_desc: "补给车队在'死亡公路'上遭到敌军伏击！",
evt_soldier_deserted: "🏃‍♂️ 无声的叛逃",
evt_soldier_deserted_desc: "一名士兵在午夜哨岗上不告而别，随身带走了一箱弹药。",
evt_weapon_malfunction: "🔧 武器故障",
evt_weapon_malfunction_desc: "新装备的武器系统出现严重故障，前线部队陷入被动。",
evt_spy_caught: "🔍 间谍暴露",
evt_spy_caught_desc: "潜伏在敌后的间谍身份暴露，遭遇了严刑拷打。",
evt_plague_outbreak: "🦠 瘟疫之影",
evt_plague_outbreak_desc: "一种未知的瘟疫在军营中迅速蔓延！",
evt_food_poisoning: "🍽️ 毒粮",
evt_food_poisoning_desc: "一批被污染的口粮导致数十名士兵食物中毒。",
evt_sabotage: "💣 破坏",
evt_sabotage_desc: "敌方特工潜入基地，在发电站安放了炸弹！",
evt_mutiny: "⚔️ 兵变",
evt_mutiny_desc: "不满情绪在部队中蔓延，一场小规模兵变爆发！",
evt_mine_collapse: "⛑️ 矿难",
evt_mine_collapse_desc: "铁矿发生严重坍塌事故，多名矿工被困井下！",
evt_bandit_raid: "🏴‍☠️ 盗匪袭击",
evt_bandit_raid_desc: "一伙全副武装的盗匪洗劫了基地的物资仓库！",

// 🟥 超级稀有事件
evt_nuclear_blueprint: "☢️ 末日图纸",
evt_nuclear_blueprint_desc: "💀 在一座废弃的军事实验室中，你发现了一份完整的核弹设计图！",
evt_alien_technology: "👽 星际遗物",
evt_alien_technology_desc: "🛸 考古队在挖掘中发现了来自远古外星文明的先进科技！",
evt_cosmic_rift: "🌀 时空裂隙",
evt_cosmic_rift_desc: "🌌 一道金色的时空裂隙在基地上空撕开，散发出惊人的能量波动！",

    // ---------- 教程 ----------
    tutorial: "主线任务",
    tutorialComplete: "✅ 任务完成！",
    tutorialReward: "奖励",

    // ---------- 广告 ----------
    adLoading: "加载广告中...",
    adComplete: "广告观看完成！",
    adFailed: "广告加载失败",
    adCooldown: "广告冷却中，请稍后",
    adDailyLimit: "今日广告次数已达上限",
    adblockDetected: "请关闭广告拦截器以获取奖励",

    // ---------- 通用 ----------
    attempts: "尝试次数",
    success: "成功次数",
    iron: "铁矿",
    level: "等级",
    pause: "停火",
    start: "出击",
    engage: "出击",
    holdFire: "停火",

    // ---------- 战争化 ----------
    battlefield: "战场",
    enemyCommander: "敌军指挥官",
    promotionTrial: "晋升试炼",
    battleStars: "战星",
    militaryRank: "军衔",
    earnBattleStars: "集满 5 颗战星即可晋升",
    welcomeCommander: "欢迎回来，指挥官",
    standingBy: "待命中...",
    engaging: "交战中...",
    victorious: "胜利！",
    defeated: "战败...",
    reinforcements: "增援抵达",

    // ---------- ★★★ 转生系统 (Part 12) ★★★ ----------
    prestige: "转生",
    prestigeTitle: "🔄 转生系统",
    prestigeDesc: "退伍重开，换取永久勋章",
    prestigeRequirement: "需要军阶达到 {rank} 才能转生",
    prestigeButton: "开始转生",
    prestigeConfirm: "⚠️ 确认转生？这将重置几乎所有进度，但永久保留勋章！",
    prestigeSuccess: "🎉 转生成功！获得 {medals} 枚勋章！",
    prestigeMedal: "🏅 勋章",
    prestigeMedals: "勋章数量",
    prestigeBonus: "资源产出 +{bonus}%",
    prestigeCount: "转生次数",
    prestigeRequirements: "转生条件",
    prestigeRewards: "转生奖励",
    prestigeWarning: "⚠️ 转生将重置：军阶、建筑、士兵、舰队、科技、装备",
    prestigeKeep: "✅ 保留：勋章、成就、每日任务进度、登录天数",
    prestigeHistory: "转生历史",
    prestigeNoHistory: "暂无转生记录",
    prestigeMaxReached: "已达最大转生次数 ({max})",
    prestigeReady: "✅ 可以转生",
    prestigeNotReady: "🔒 未达到转生条件",
    offlineCapNotice: "💡 离线收益已封顶 12 小时（超出部分不计）"
  },

  en: {
    // ---------- UI Core ----------
    rank: "Military Rank",
    stars: "Battle Stars",
    exp: "EXP",
    gold: "Gold",
    cp: "CP",
    kill: "Kills",
    boss: "Enemy Commander",
    autoFight: "Battlefield",
    offlineEarning: "Offline Earnings",
    doubleReward: "Double Claim",
    promotion: "Promotion Trial",
    trialPass: "✅ Trial Passed! Promoted!",
    trialFail: "❌ Trial Failed! Keep fighting!",
    normalTrial: "Standard Trial 50%",
    premiumTrial: "Military Funds 70%",
    watchAd: "Watch Ad 100%",
    starsFull: "★★★★★ Battle Stars Full! Ready to Promote!",
    save: "Save",
    load: "Load",
    claim: "Claim",
    confirm: "Confirm",
    cancel: "Cancel",

    // ---------- Promotion ----------
    promoteNormal: "Standard Trial",
    promoteGold: "Military Funds",
    promoteAd: "Recommendation",
    promoteNormalDesc: "Cost EXP, 50% chance",
    promoteGoldDesc: "Cost Gold, 70% chance",
    promoteAdDesc: "Watch Ad, 100% success",
    failPenalty: "Fail: -50% EXP",
    goldLost: "Gold lost on fail",
    guaranteed: "Guaranteed",

    // ---------- Story ----------
    storyTitle: "⭐ War Log",
    storySkip: "Skip",
    storyContinue: "Continue ▶",

    // ---------- Buildings ----------
    building: "Base Facilities",
    goldMine: "Gold Mine",
    ironMine: "Iron Mine",
    riceFarm: "Rice Farm",
    barracks: "Barracks",
    hospital: "Field Hospital",
    buildingMaxLevel: "Max level for current rank",
    notEnoughGold: "Not enough gold!",
    buildingUpgraded: "Facility upgraded!",
    buildingProduction: "Base Production",

    // ---------- Soldiers ----------
    soldier: "Soldier",
    soldiers: "Soldiers",
    train: "Train",
    trainSoldier: "Train Soldier",
    treat: "Heal",
    treatWounded: "Heal Wounded",
    wounded: "Wounded",
    totalSoldiers: "Total Soldiers",
    soldierMax: "Max Soldiers",
    ricePerSecond: "Rice/sec",
    trainCost: "Training Cost",
    healCost: "Heal Cost",
    noWounded: "No wounded soldiers",
    maxSoldiersReached: "Max soldiers reached",
    notEnoughRice: "Not enough rice!",
    soldierTrained: "Soldier trained!",
    soldierTrainedAd: "Soldier trained! (Ad Boost)",
    soldierHealed: "Wounded healed!",
    soldierHealedAd: "Wounded healed! (Ad Boost)",
    soldierDied: "A soldier died in combat",

    // ---------- Fleet ----------
    fleet: "Fleet",
    fleetUpgrade: "Upgrade Ship",
    fleetLocked: "Locked",
    fleetLevel: "Level",
    fleetCp: "Fleet Firepower",
    fleetMaxLevel: "Max level reached",
    notEnoughIron: "Not enough iron!",
    fleetUpgraded: "Ship upgraded!",
    fleetUpgradedAd: "Ship upgraded! (Ad Boost)",

    // ---------- Tech ----------
    tech: "Tech Tree",
    techPoint: "Tech Points",
    techUpgrade: "Research",
    techLocked: "Locked",
    techMaxLevel: "Max level reached",
    techEffectCp: "+CP",
    techEffectIncome: "+Income",
    techEffectArmor: "-Soldier Death",
    techEffectRadar: "-Boss Interval",
    techEffectAI: "+Combat Efficiency",
    techEffectBoss: "+Boss Damage",
    techEffectAll: "+All Stats",
    techUpgraded: "Tech researched!",
    techUpgradedAd: "Tech researched! (Ad Boost)",
    techPointGain: "Tech Points gained",
    notEnoughTechPoint: "Not enough tech points!",

    // ---------- Equipment ----------
    equipment: "Armaments",
    equipUpgrade: "Upgrade Gear",
    equipLocked: "Locked",
    equipMaxLevel: "Max level reached",
    equipCp: "+CP",
    equipArmor: "-Death Rate",
    equipIncome: "+Income",
    equipBoss: "+Boss Damage",
    equipEfficiency: "+Combat Efficiency",
    equipAll: "+All Stats",
    equipUpgraded: "Gear upgraded!",
    equipUpgradedAd: "Gear upgraded! (Ad Boost)",

    // ---------- Daily ----------
    dailyQuest: "Daily Quest",
    dailyQuests: "Daily Quests",
    dailyReset: "Daily Reset",
    dailyProgress: "Progress",
    dailyClaim: "Claim Reward",
    dailyCompleted: "Completed",
    dailyIncomplete: "Incomplete",
    dailyReward: "Reward",
    dailyDone: "✅ Done",
    dailyClaimed: "Claimed",

    // ---------- Login ----------
    loginCheckIn: "Daily Login",
    loginDay: "Day {day}",
    loginStreak: "{streak} day streak",
    loginClaim: "Claim Login",
    loginReward: "Login Reward",
    loginSpecial: "🎉 Super Reward!",
    loginAllClaimed: "🎉 All login rewards claimed!",
    loginStreakBroken: "⚠️ Login streak broken, reset",
    loginAlreadyClaimed: "📅 Already claimed today",

    // ---------- Achievements ----------
    achievement: "Achievement",
    achievements: "Achievements",
    achievementUnlocked: "🎖️ Achievement Unlocked!",
    achievementLocked: "Locked",
    achievementProgress: "Progress",
    achievementReward: "Reward",

    // ---------- Events ----------
    event: "Battle Event",
    eventTitle: "⚡ Battle Event",
    eventClaim: "Claim Loot",
    eventDismiss: "Dismiss",
    eventAdBonus: "📺 Ad Reward ×2",
    eventNoAd: "Ad failed, normal reward claimed",
    eventBuff: "🔁 Double Rewards Buff",

// ===== Movie-Style Event Translations - English =====
// 🟢 Good Events
evt_spy_intel: "🕵️ Operation: Shadow Strike",
evt_spy_intel_desc: "A deep-cover spy has stolen the enemy's primary battle plan!",
evt_gold_mine: "⛏️ The Gold Rush",
evt_gold_mine_desc: "Prospectors have discovered a massive gold vein in the abandoned mines!",
evt_united_nations: "🌍 Humanitarian Intervention",
evt_united_nations_desc: "The UN has dispatched a humanitarian fleet to the front lines.",
evt_scientist_joins: "👨‍🔬 The Genius Arrives",
evt_scientist_joins_desc: "Nobel laureate Dr. Erin Klaus has joined your research team!",
evt_morale_boost: "🎖️ Band of Brothers",
evt_morale_boost_desc: "Soldiers forged deep bonds during a joint operation, morale is sky-high.",
evt_weapon_test: "🔫 Project Titan",
evt_weapon_test_desc: "The classified 'Project Titan' weapon system test was a complete success!",
evt_supply_drop: "📦 Operation Anvil",
evt_supply_drop_desc: "The 'Anvil' supply drone has successfully breached enemy air defenses.",
evt_scout_returns: "🔭 Behind Enemy Lines",
evt_scout_returns_desc: "The recon team returned after 72 hours behind enemy lines with critical intel.",
evt_enemy_armory: "💣 Armory Assault",
evt_enemy_armory_desc: "Commandos successfully infiltrated and destroyed the enemy's strategic armory!",
evt_reinforcements: "🚁 The Cavalry Arrives",
evt_reinforcements_desc: "The 7th Air Cavalry has arrived! The bagpipes are playing!",
evt_treasure_map: "🗺️ The Lost Treasure",
evt_treasure_map_desc: "A soldier found an ancient map marked with 'El Dorado' at an abandoned outpost.",
evt_training_camp: "🏋️ Boot Camp",
evt_training_camp_desc: "Recruits completed 'Hell Week' under the toughest drill instructors!",
evt_trading_post: "🏪 The Bazaar",
evt_trading_post_desc: "The border bazaar has rare supplies available.",
evt_diplomatic_mission: "🤝 Peace Talks",
evt_diplomatic_mission_desc: "The diplomatic mission has secured a temporary peace agreement.",
evt_engineering_breakthrough: "⚙️ Breakthrough",
evt_engineering_breakthrough_desc: "Engineers made a revolutionary breakthrough in propulsion technology!",
evt_medical_supplies: "💊 M*A*S*H",
evt_medical_supplies_desc: "A M*A*S*H unit has arrived with full medical supplies!",
evt_strategic_position: "🏔️ The High Ground",
evt_strategic_position_desc: "Forces have captured the strategic position known as 'King's Mountain'!",
evt_war_hero: "🎖️ The Medal of Honor",
evt_war_hero_desc: "Corporal John Miller has been awarded the Medal of Honor for bravery!",
evt_crops_harvest: "🌾 Harvest Moon",
evt_crops_harvest_desc: "The rice fields have yielded a historic, bountiful harvest!",
evt_iron_vein: "⛏️ The Iron Vein",
evt_iron_vein_desc: "A high-purity iron vein has been discovered in the southern mountains!",

// 🟡 Normal Events
evt_civilian_plea: "👥 War Refugees",
evt_civilian_plea_desc: "War refugees have gathered at the base gate, seeking shelter and food.",
evt_merchant_visit: "🧳 The Black Marketeer",
evt_merchant_visit_desc: "A black market dealer known as 'The Fox' has arrived with 'special' goods.",
evt_abandoned_base: "🏚️ The Ruined Outpost",
evt_abandoned_base_desc: "Scouts discovered an abandoned military outpost with usable supplies.",
evt_recruit_volunteers: "🪖 Volunteers",
evt_recruit_volunteers_desc: "The call to arms has brought volunteers to the recruitment office.",
evt_pmc_contract: "📋 The Contract",
evt_pmc_contract_desc: "A PMC company offers a lucrative contract: destroy the enemy radar station.",
evt_refugee_camp: "⛺ Refugee Camp",
evt_refugee_camp_desc: "A refugee camp is sheltering displaced civilians on the border.",
evt_lost_convoy: "🚚 The Abandoned Convoy",
evt_lost_convoy_desc: "An abandoned supply convoy was found in the desert, apparently attacked.",
evt_deserters: "🏃 The Defectors",
evt_deserters_desc: "Three deserters defected to your forces at night, bringing enemy intel.",
evt_radio_transmission: "📻 Ghost Signal",
evt_radio_transmission_desc: "The comms station intercepted an encrypted signal from an unknown source.",
evt_field_hospital: "🏥 Field Hospital",
evt_field_hospital_desc: "Medics are fighting against time to save the wounded.",
evt_old_soldier: "🧓 The Veteran",
evt_old_soldier_desc: "A three-war veteran has reported for duty, bringing invaluable experience.",
evt_storm_warning: "🌩️ Before the Storm",
evt_storm_warning_desc: "Weather station reports a massive storm approaching. Prepare defenses.",
evt_friendly_fire: "🔥 Friendly Fire",
evt_friendly_fire_desc: "A night patrol misidentified friendlies as enemies, causing casualties.",
evt_black_market: "🏴 Black Market",
evt_black_market_desc: "On the black market, someone is trading iron and rice for gold.",
evt_supply_shortage: "📉 Supply Crisis",
evt_supply_shortage_desc: "The supply line has been cut! Frontline supplies are critically low!",
evt_secret_tunnel: "🚇 The Secret Tunnel",
evt_secret_tunnel_desc: "An engineer discovered an abandoned tunnel leading to enemy headquarters!",
evt_ceasefire: "🕊️ Ceasefire",
evt_ceasefire_desc: "A 72-hour temporary ceasefire has been brokered by the Red Cross.",
evt_ancient_ruins: "🏛️ The Lost Civilization",
evt_ancient_ruins_desc: "The ruins of a lost civilization have been discovered, holding untold secrets.",
evt_diplomatic_incident: "📜 Diplomatic Incident",
evt_diplomatic_incident_desc: "A diplomatic incident has caused a major controversy.",
evt_wildlife_attack: "🐺 Beast Attack",
evt_wildlife_attack_desc: "A pack of hungry sand wolves attacked the base perimeter!",
evt_desert_storm: "🌪️ Desert Storm",
evt_desert_storm_desc: "A massive desert storm is destroying everything in its path!",

// 🔴 Bad Events
evt_enemy_air_raid: "✈️ Black Tuesday",
evt_enemy_air_raid_desc: "The enemy launched a massive air raid, codenamed 'Black Tuesday'!",
evt_convoy_ambushed: "💥 Highway of Death",
evt_convoy_ambushed_desc: "The supply convoy was ambushed on the 'Highway of Death'!",
evt_soldier_deserted: "🏃‍♂️ Silent Defection",
evt_soldier_deserted_desc: "A soldier vanished from the midnight guard post with a case of ammunition.",
evt_weapon_malfunction: "🔧 Weapon Malfunction",
evt_weapon_malfunction_desc: "New weapon systems suffered a critical failure, frontlines are compromised.",
evt_spy_caught: "🔍 Spy Exposed",
evt_spy_caught_desc: "A deep-cover spy has been exposed and captured by the enemy.",
evt_plague_outbreak: "🦠 Shadow of Plague",
evt_plague_outbreak_desc: "An unknown plague is rapidly spreading through the camp!",
evt_food_poisoning: "🍽️ Poisoned Rations",
evt_food_poisoning_desc: "Contaminated rations have caused food poisoning among dozens of soldiers.",
evt_sabotage: "💣 Sabotage",
evt_sabotage_desc: "Enemy agents have infiltrated the base and planted bombs at the power station!",
evt_mutiny: "⚔️ Mutiny",
evt_mutiny_desc: "Discontent has spread among the ranks, a minor mutiny has erupted!",
evt_mine_collapse: "⛑️ Mine Disaster",
evt_mine_collapse_desc: "A major collapse at the iron mine has trapped dozens of miners!",
evt_bandit_raid: "🏴‍☠️ Bandit Raid",
evt_bandit_raid_desc: "Heavily armed bandits have raided the base supply depot!",

// 🟥 Legendary Events
evt_nuclear_blueprint: "☢️ The Doomsday Blueprint",
evt_nuclear_blueprint_desc: "💀 In an abandoned military lab, you discovered a complete nuclear weapon blueprint!",
evt_alien_technology: "👽 Stellar Relic",
evt_alien_technology_desc: "🛸 Archaeologists have uncovered advanced technology from an ancient alien civilization!",
evt_cosmic_rift: "🌀 The Cosmic Rift",
evt_cosmic_rift_desc: "🌌 A golden cosmic rift has torn open above the base, radiating immense energy!",

    // ---------- Tutorial ----------
    tutorial: "Main Quest",
    tutorialComplete: "✅ Quest Complete!",
    tutorialReward: "Reward",

    // ---------- Ads ----------
    adLoading: "Loading ad...",
    adComplete: "Ad complete!",
    adFailed: "Ad failed to load",
    adCooldown: "Ad cooldown, please wait",
    adDailyLimit: "Daily ad limit reached",
    adblockDetected: "Please disable adblocker",

    // ---------- Common ----------
    attempts: "Attempts",
    success: "Success",
    iron: "Iron",
    level: "Level",
    pause: "Hold Fire",
    start: "Engage",
    engage: "Engage",
    holdFire: "Hold Fire",

    // ---------- War Themed ----------
    battlefield: "Battlefield",
    enemyCommander: "Enemy Commander",
    promotionTrial: "Promotion Trial",
    battleStars: "Battle Stars",
    militaryRank: "Military Rank",
    earnBattleStars: "Earn 5 Battle Stars to promote",
    welcomeCommander: "Welcome back, Commander",
    standingBy: "Standing by...",
    engaging: "Engaging...",
    victorious: "Victorious!",
    defeated: "Defeated...",
    reinforcements: "Reinforcements arrived",

    // ---------- ★★★ Prestige System (Part 12) ★★★ ----------
    prestige: "Prestige",
    prestigeTitle: "🔄 Prestige System",
    prestigeDesc: "Retire and reset for permanent medals",
    prestigeRequirement: "Requires rank {rank} to prestige",
    prestigeButton: "Start Prestige",
    prestigeConfirm: "⚠️ Confirm Prestige? This will reset most progress but keep medals!",
    prestigeSuccess: "🎉 Prestige successful! Gained {medals} medals!",
    prestigeMedal: "🏅 Medal",
    prestigeMedals: "Medals",
    prestigeBonus: "+{bonus}% Resource Production",
    prestigeCount: "Prestige Count",
    prestigeRequirements: "Requirements",
    prestigeRewards: "Rewards",
    prestigeWarning: "⚠️ Prestige will reset: Rank, Buildings, Soldiers, Fleet, Tech, Equipment",
    prestigeKeep: "✅ Keeps: Medals, Achievements, Daily Progress, Login Days",
    prestigeHistory: "Prestige History",
    prestigeNoHistory: "No prestige history",
    prestigeMaxReached: "Max prestige reached ({max})",
    prestigeReady: "✅ Ready to Prestige",
    prestigeNotReady: "🔒 Conditions not met",
    offlineCapNotice: "💡 Offline earnings capped at 12 hours"
  }
};

// Current language
let langCurrent = 'en';

function t(key) {
  return LANG[langCurrent][key] || key;
}

function switchLang(lang) {
  if (LANG[lang]) {
    langCurrent = lang;
    localStorage.setItem('commander_lang', lang);
    if (typeof updateUI === 'function') updateUI();
    updateStartScreenLang();
  }
}

function updateStartScreenLang() {
  const isZh = langCurrent === 'zh';
  const startBtn = document.querySelector('#gs-container .btn-start');
  if (startBtn) startBtn.textContent = isZh ? '开始指挥' : 'Begin Command';
  const zhBtn = document.getElementById('lang-zh-btn');
  const enBtn = document.getElementById('lang-en-btn');
  if (zhBtn) zhBtn.textContent = isZh ? '中文' : 'Chinese';
  if (enBtn) enBtn.textContent = isZh ? 'English' : 'English';
  const info = document.getElementById('save-info');
  if (info) {
    const hasSave = localStorage.getItem('commander_save') ? true : false;
    info.textContent = hasSave ? (isZh ? '📁 存档已加载' : '📁 Save Loaded') : (isZh ? '📁 新游戏' : '📁 New Game');
  }
}

if (localStorage.getItem('commander_lang')) {
  langCurrent = localStorage.getItem('commander_lang');
}